# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MegaOrganised' do
pod "Color-Picker-for-iOS", "~> 2.0"
pod 'PDTSimpleCalendar', '~> 0.7.0'
pod 'MBCalendarKit', '~>2.2.2'
end

target 'MegaOrganisedTests' do

end

